"""Pydantic domain models. Used as LLM output schemas, DB serialization shape, and API contracts."""
from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


Level = Literal["beginner", "intermediate", "advanced"]


# ---------- Plan generation ----------

class PlanDay(BaseModel):
    """One day of a curriculum."""
    day_num: int = Field(ge=1, description="1-indexed day number")
    topic: str = Field(min_length=3, description="High-level topic for this day")
    objective: str = Field(min_length=10, description="What the learner should be able to do by end of day")
    concepts: list[str] = Field(
        min_length=1, max_length=8,
        description="Atomic concepts to internalize today (short noun phrases)",
    )
    activities: list[str] = Field(
        default_factory=list,
        description="Concrete things to do today (read X, implement Y, watch Z)",
    )
    suggested_resources: list[str] = Field(
        default_factory=list,
        description="Resource suggestions — names/types are fine, exact URLs not required",
    )
    checkpoint: str = Field(
        default="",
        description="A concrete artifact or demonstration that proves the day's objective was met.",
    )
    success_criteria: list[str] = Field(
        default_factory=list,
        description="2-4 observable criteria used to evaluate the checkpoint.",
    )
    estimated_minutes: int = Field(default=60, ge=15, le=480)
    difficulty: Literal["foundation", "core", "stretch", "synthesis"] = "core"


class Plan(BaseModel):
    """A day-by-day curriculum generated by the planner agent."""
    reasoning: str = Field(
        description="Step-by-step thinking BEFORE the plan: concept decomposition, "
                    "dependency ordering, pacing rationale. 3-6 sentences."
    )
    self_check: str = Field(
        description="Verifications done after drafting: day count matches deadline, "
                    "dependency order is sound, last day is synthesis, activities are concrete."
    )
    reasoning_types: list[str] = Field(
        default_factory=list,
        description="Tags for the kinds of reasoning used (e.g. 'decomposition', "
                    "'dependency-analysis', 'pacing-estimation').",
    )
    caveats: list[str] = Field(
        default_factory=list,
        description="Honest notes about limits — e.g. 'goal is broad; this is one slice', "
                    "'deadline is tight, full mastery needs more time'. Empty if none.",
    )
    goal: str = Field(description="Restatement of the learning goal")
    summary: str = Field(description="2-3 sentence overview of the arc")
    total_days: int = Field(ge=1, le=90)
    days: list[PlanDay] = Field(min_length=1)


# ---------- Check-in ----------

QuestionKind = Literal["feynman", "quiz"]


class Question(BaseModel):
    """One question the check-in agent asks the learner."""
    kind: QuestionKind
    concept: str = Field(description="Which concept (must match one in today's PlanDay) this targets")
    prompt: str = Field(description="The exact question text shown to the learner")
    difficulty: Literal["foundation", "application", "analysis"] = "application"
    intent: str = Field(default="", description="The diagnostic purpose of this question.")
    expected_elements: list[str] = Field(
        default_factory=list,
        description="Concrete elements a strong answer should contain.",
    )


class CheckInPlan(BaseModel):
    """The set of questions the agent will ask today, planned up-front."""
    reasoning: str = Field(
        description="Why these specific questions — which concepts are weakest, which "
                    "are unassessed, what each question is designed to surface. 3-5 sentences."
    )
    self_check: str = Field(
        description="Verifications: each question.concept matches today's concept list, "
                    "exactly 1 feynman + 2 quiz, questions are answerable in 2-5 sentences."
    )
    questions: list[Question] = Field(min_length=2, max_length=5)


Confidence = Literal["high", "medium", "low"]


class GradedAnswer(BaseModel):
    """Output of the grader agent for a single answer."""
    reasoning: str = Field(
        description="Step-by-step analysis of what the answer got right and wrong, "
                    "matched against the rubric and concept. 2-4 sentences."
    )
    confidence: Confidence = Field(
        description="How confident you are in the grade. 'low' if the answer is short, "
                    "ambiguous, off-topic, or the question itself is genuinely contestable."
    )
    self_check: str = Field(
        description="Verification: does the numeric score align with the feedback you wrote? "
                    "Did you avoid penalizing for jargon vs. real understanding?"
    )
    score: float = Field(ge=0.0, le=1.0, description="0=wrong, 0.5=partial/shaky, 1=solid")
    correct: bool = Field(description="Approximately correct?")
    feedback: str = Field(description="Short feedback for the learner (1-3 sentences)")
    gaps: list[str] = Field(
        default_factory=list,
        description="Specific concept gaps revealed by this answer",
    )


class CheckInAnswer(BaseModel):
    """A learner's answer to one question, plus its grade."""
    question: Question
    answer_text: str
    grade: GradedAnswer


class CheckInResult(BaseModel):
    """Output of a full check-in session."""
    plan_day_id: int
    answers: list[CheckInAnswer]
    overall_score: float = Field(ge=0.0, le=1.0)
    next_focus: list[str] = Field(
        default_factory=list,
        description="Concepts the next session should revisit",
    )


# ---------- Feynman checks (Mode 2) ----------

FeynmanVerdict = Literal["probe", "solid"]


class FeynmanTurn(BaseModel):
    """The tutor's evaluation of one learner explanation, plus its next move."""
    reasoning: str = Field(
        description="What the explanation got right, what's missing, vague, or wrong — "
                    "matched against a mental rubric for the concept. 2-4 sentences."
    )
    self_check: str = Field(
        description="Verification: is the verdict consistent with the gaps you found? "
                    "Did you judge real understanding rather than vocabulary? Is follow_up "
                    "non-empty iff verdict='probe'?"
    )
    understanding: float = Field(
        ge=0.0, le=1.0,
        description="How solid the explanation is so far. 0=no grasp, 0.5=partial, "
                    "1=could teach it cleanly.",
    )
    gaps: list[str] = Field(
        default_factory=list,
        description="Specific things missing, muddled, or wrong in the explanation.",
    )
    verdict: FeynmanVerdict = Field(
        description="'solid' when the explanation is complete and correct; "
                    "'probe' when one more follow-up is warranted.",
    )
    follow_up: str = Field(
        default="",
        description="The next question to ask, targeting the SINGLE biggest gap. "
                    "Required (non-empty) when verdict='probe'; empty when 'solid'.",
    )
    feedback: str = Field(description="Short, encouraging note to the learner (1-2 sentences).")


class FeynmanExchange(BaseModel):
    """One round of a Feynman session: question asked, learner's explanation, tutor's eval."""
    question: str
    answer: str
    turn: FeynmanTurn


class FeynmanResult(BaseModel):
    """A completed Feynman session for one concept."""
    goal_id: int
    concept: str
    exchanges: list[FeynmanExchange]
    final_understanding: float = Field(ge=0.0, le=1.0)
    solved: bool = Field(description="True if the learner reached a 'solid' verdict (vs. hit the turn cap).")


# ---------- Resource verification (web-search tool) ----------

class SearchHit(BaseModel):
    """One result from the web-search tool."""
    title: str
    url: str
    snippet: str = ""


class VerifiedResource(BaseModel):
    """A learning resource the verifier checked against real search results."""
    name: str = Field(description="Human-readable resource name/title")
    url: str = Field(
        default="",
        description="A real URL taken from the provided search results. Empty if none matched.",
    )
    kind: str = Field(
        default="",
        description="Type tag: 'video', 'article', 'paper', 'course', 'docs', 'book', etc.",
    )
    verified: bool = Field(description="True ONLY if a real matching URL from the search results is attached.")
    note: str = Field(default="", description="Why verified/unverified, or what the resource covers (1 sentence).")


class ResourceCheck(BaseModel):
    """Output of the resource-verifier agent for one plan day."""
    reasoning: str = Field(
        description="How you matched the planner's suggested resources to real search hits; "
                    "which you could and couldn't verify, and why. 2-4 sentences."
    )
    self_check: str = Field(
        description="Verification: every non-empty `url` comes from the provided search results "
                    "(NOT invented); `verified` is true iff a real URL is attached."
    )
    resources: list[VerifiedResource] = Field(default_factory=list)


# ---------- API request models ----------

class CreateGoalRequest(BaseModel):
    text: str = Field(min_length=8, max_length=500, description="Free-form learning goal")
    level: Level = "beginner"
    deadline_days: int = Field(ge=1, le=90)
    user_id: int = Field(default=1, ge=1)
    provider: Optional[str] = Field(
        default=None,
        description="Provider override (e.g. 'gemini', 'groq', 'auto'). None = use PLANNER_PROVIDER env",
    )


class RefinePlanRequest(BaseModel):
    instruction: str = Field(min_length=4, max_length=1000, description="What to change about the current plan")
    provider: Optional[str] = None


class SubmitAnswerRequest(BaseModel):
    question_index: int = Field(ge=0)
    answer_text: str = Field(min_length=1)


class StartFeynmanRequest(BaseModel):
    goal_id: int
    concept: str = Field(min_length=1, max_length=200)


class FeynmanReplyRequest(BaseModel):
    session: str = Field(min_length=1, description="Session token returned by /feynman/start")
    answer_text: str = Field(min_length=1)


# ---------- Remaining learning modes ----------

class FlashcardRow(BaseModel):
    id: int
    goal_id: int
    concept: str
    front: str
    back: str
    due_at: datetime
    stability: float = 1.0
    difficulty: float = 5.0
    reps: int = 0
    lapses: int = 0


class FlashcardDraft(BaseModel):
    concept: str = Field(min_length=2, max_length=200)
    front: str = Field(min_length=12, max_length=500)
    back: str = Field(min_length=20, max_length=1500)
    card_type: Literal["concept", "mechanism", "application", "contrast", "failure-mode"]
    difficulty: Literal["foundation", "application", "analysis"] = "application"


class FlashcardSet(BaseModel):
    rationale: str = Field(min_length=20)
    cards: list[FlashcardDraft] = Field(min_length=3, max_length=30)


class ReviewFlashcardRequest(BaseModel):
    rating: Literal[1, 2, 3, 4] = Field(
        description="1=again, 2=hard, 3=good, 4=easy",
    )


class AdaptiveQuizRequest(BaseModel):
    goal_id: int
    count: int = Field(default=5, ge=1, le=12)


class AdaptiveQuizAnswerRequest(BaseModel):
    session: str
    question_index: int = Field(ge=0)
    answer_text: str = Field(min_length=1)


class SocraticStartRequest(BaseModel):
    goal_id: int
    concept: str = Field(min_length=1, max_length=200)


class SocraticReplyRequest(BaseModel):
    session: str
    answer_text: str = Field(min_length=1)


class SocraticTurn(BaseModel):
    feedback: str
    question: str
    understanding: float = Field(ge=0.0, le=1.0)
    complete: bool = False


class NoteRow(BaseModel):
    id: int
    goal_id: int
    filename: str
    content: str
    concepts: list[str] = Field(default_factory=list)
    created_at: datetime


class CreateUserRequest(BaseModel):
    name: str = Field(min_length=1, max_length=80)


class CreateRoadmapTargetRequest(BaseModel):
    title: str = Field(min_length=3, max_length=160)
    description: str = Field(default="", max_length=500)
    target_type: Literal["mastery", "checkpoint", "practice"] = "checkpoint"
    target_value: float = Field(default=1.0, ge=0.0, le=100.0)
    concept: Optional[str] = Field(default=None, max_length=200)


class UpdateRoadmapTargetRequest(BaseModel):
    completed: bool


class UserRow(BaseModel):
    id: int
    name: str
    created_at: datetime


class ConceptNode(BaseModel):
    concept: str
    mastery: float = 0.0
    samples: int = 0
    day_nums: list[int] = Field(default_factory=list)
    prerequisites: list[str] = Field(default_factory=list)


# ---------- Stored / view models (DB-aware) ----------

class GoalRow(BaseModel):
    id: int
    user_id: int = 1
    text: str
    level: Level
    deadline_days: int
    created_at: datetime


class PlanRow(BaseModel):
    id: int
    goal_id: int
    version: int
    summary: str
    reasoning: str = ""
    self_check: str = ""
    reasoning_types: list[str] = Field(default_factory=list)
    caveats: list[str] = Field(default_factory=list)
    total_days: int
    created_at: datetime


class PlanDayRow(BaseModel):
    id: int
    plan_id: int
    day_num: int
    topic: str
    objective: str
    concepts: list[str]
    activities: list[str]
    suggested_resources: list[str]
    checkpoint: str = ""
    success_criteria: list[str] = Field(default_factory=list)
    estimated_minutes: int = 60
    difficulty: Literal["foundation", "core", "stretch", "synthesis"] = "core"
    status: Literal["pending", "in_progress", "done"] = "pending"


class MasteryRow(BaseModel):
    concept: str
    score: float
    samples: int
    last_assessed: Optional[datetime] = None
