"""Pydantic domain models. Used as LLM output schemas, DB serialization shape, and API contracts."""
from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


Level = Literal["beginner", "intermediate", "advanced"]


# ---------- Plan generation ----------

class PlanDay(BaseModel):
    """One day of a curriculum."""
    day_num: int = Field(ge=1, description="1-indexed day number")
    topic: str = Field(min_length=3, description="High-level topic for this day")
    objective: str = Field(min_length=10, description="What the learner should be able to do by end of day")
    concepts: list[str] = Field(
        min_length=1, max_length=8,
        description="Atomic concepts to internalize today (short noun phrases)",
    )
    activities: list[str] = Field(
        default_factory=list,
        description="Concrete things to do today (read X, implement Y, watch Z)",
    )
    suggested_resources: list[str] = Field(
        default_factory=list,
        description="Resource suggestions — names/types are fine, exact URLs not required",
    )


class Plan(BaseModel):
    """A day-by-day curriculum generated by the planner agent."""
    reasoning: str = Field(
        description="Step-by-step thinking BEFORE the plan: concept decomposition, "
                    "dependency ordering, pacing rationale. 3-6 sentences."
    )
    self_check: str = Field(
        description="Verifications done after drafting: day count matches deadline, "
                    "dependency order is sound, last day is synthesis, activities are concrete."
    )
    reasoning_types: list[str] = Field(
        default_factory=list,
        description="Tags for the kinds of reasoning used (e.g. 'decomposition', "
                    "'dependency-analysis', 'pacing-estimation').",
    )
    caveats: list[str] = Field(
        default_factory=list,
        description="Honest notes about limits — e.g. 'goal is broad; this is one slice', "
                    "'deadline is tight, full mastery needs more time'. Empty if none.",
    )
    goal: str = Field(description="Restatement of the learning goal")
    summary: str = Field(description="2-3 sentence overview of the arc")
    total_days: int = Field(ge=1, le=90)
    days: list[PlanDay] = Field(min_length=1)


# ---------- Check-in ----------

QuestionKind = Literal["feynman", "quiz"]


class Question(BaseModel):
    """One question the check-in agent asks the learner."""
    kind: QuestionKind
    concept: str = Field(description="Which concept (must match one in today's PlanDay) this targets")
    prompt: str = Field(description="The exact question text shown to the learner")


class CheckInPlan(BaseModel):
    """The set of questions the agent will ask today, planned up-front."""
    reasoning: str = Field(
        description="Why these specific questions — which concepts are weakest, which "
                    "are unassessed, what each question is designed to surface. 3-5 sentences."
    )
    self_check: str = Field(
        description="Verifications: each question.concept matches today's concept list, "
                    "exactly 1 feynman + 2 quiz, questions are answerable in 2-5 sentences."
    )
    questions: list[Question] = Field(min_length=2, max_length=5)


Confidence = Literal["high", "medium", "low"]


class GradedAnswer(BaseModel):
    """Output of the grader agent for a single answer."""
    reasoning: str = Field(
        description="Step-by-step analysis of what the answer got right and wrong, "
                    "matched against the rubric and concept. 2-4 sentences."
    )
    confidence: Confidence = Field(
        description="How confident you are in the grade. 'low' if the answer is short, "
                    "ambiguous, off-topic, or the question itself is genuinely contestable."
    )
    self_check: str = Field(
        description="Verification: does the numeric score align with the feedback you wrote? "
                    "Did you avoid penalizing for jargon vs. real understanding?"
    )
    score: float = Field(ge=0.0, le=1.0, description="0=wrong, 0.5=partial/shaky, 1=solid")
    correct: bool = Field(description="Approximately correct?")
    feedback: str = Field(description="Short feedback for the learner (1-3 sentences)")
    gaps: list[str] = Field(
        default_factory=list,
        description="Specific concept gaps revealed by this answer",
    )


class CheckInAnswer(BaseModel):
    """A learner's answer to one question, plus its grade."""
    question: Question
    answer_text: str
    grade: GradedAnswer


class CheckInResult(BaseModel):
    """Output of a full check-in session."""
    plan_day_id: int
    answers: list[CheckInAnswer]
    overall_score: float = Field(ge=0.0, le=1.0)
    next_focus: list[str] = Field(
        default_factory=list,
        description="Concepts the next session should revisit",
    )


# ---------- API request models ----------

class CreateGoalRequest(BaseModel):
    text: str = Field(min_length=8, max_length=500, description="Free-form learning goal")
    level: Level = "beginner"
    deadline_days: int = Field(ge=1, le=90)
    provider: Optional[str] = Field(
        default=None,
        description="Provider override (e.g. 'gemini', 'groq', 'auto'). None = use PLANNER_PROVIDER env",
    )


class RefinePlanRequest(BaseModel):
    instruction: str = Field(min_length=4, max_length=1000, description="What to change about the current plan")
    provider: Optional[str] = None


class SubmitAnswerRequest(BaseModel):
    question_index: int = Field(ge=0)
    answer_text: str = Field(min_length=1)


# ---------- Stored / view models (DB-aware) ----------

class GoalRow(BaseModel):
    id: int
    text: str
    level: Level
    deadline_days: int
    created_at: datetime


class PlanRow(BaseModel):
    id: int
    goal_id: int
    version: int
    summary: str
    reasoning: str = ""
    self_check: str = ""
    reasoning_types: list[str] = Field(default_factory=list)
    caveats: list[str] = Field(default_factory=list)
    total_days: int
    created_at: datetime


class PlanDayRow(BaseModel):
    id: int
    plan_id: int
    day_num: int
    topic: str
    objective: str
    concepts: list[str]
    activities: list[str]
    suggested_resources: list[str]
    status: Literal["pending", "in_progress", "done"] = "pending"


class MasteryRow(BaseModel):
    concept: str
    score: float
    samples: int
    last_assessed: Optional[datetime] = None
